## Importing librabries

In [2]:
! pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import tensorflow as tf 
import matplotlib.pyplot as plt
import seaborn as sns

## Data preprocessing

In [7]:
training_set = tf.keras.utils.image_dataset_from_directory(
  'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    
)

Found 2823 files belonging to 38 classes.


In [8]:
validation_set = tf.keras.utils.image_dataset_from_directory(
  'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
   
)

Found 6782 files belonging to 38 classes.


In [11]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [14]:
for x, y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[172.   164.   175.  ]
   [173.25 165.25 176.25]
   [177.   169.   180.  ]
   ...
   [177.   170.   178.  ]
   [184.   177.   185.  ]
   [178.75 171.75 179.75]]

  [[176.75 168.75 179.75]
   [175.5  167.5  178.5 ]
   [175.25 167.25 178.25]
   ...
   [182.   175.   183.  ]
   [174.   167.   175.  ]
   [168.25 161.25 169.25]]

  [[175.5  167.5  178.5 ]
   [174.25 166.25 177.25]
   [174.   166.   177.  ]
   ...
   [180.5  173.5  181.5 ]
   [186.25 179.25 187.25]
   [167.75 160.75 168.75]]

  ...

  [[161.5  153.5  164.5 ]
   [157.25 149.25 160.25]
   [151.5  143.5  154.5 ]
   ...
   [140.   130.   139.  ]
   [136.75 126.75 135.75]
   [145.   135.   144.  ]]

  [[150.75 142.75 153.75]
   [160.75 152.75 163.75]
   [157.75 149.75 160.75]
   ...
   [146.25 136.25 145.25]
   [141.25 131.25 140.25]
   [156.   146.   155.  ]]

  [[139.5  131.5  142.5 ]
   [149.25 141.25 152.25]
   [151.25 143.25 154.25]
   ...
   [140.5  130.5  139.5 ]
   [149.   139.   148.  ]
   [143.   133.   14

In [16]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from tensorflow.keras.models import Sequential

In [18]:
model= Sequential()

In [20]:
# Bulding Convolution layer

In [22]:
model.add(Conv2D(filters=32, kernel_size=3, padding="same", activation="relu",input_shape=[128,128,3]))
model.add(Conv2D(filters=32, kernel_size=3, padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=2,strides=2))

C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [24]:
model.add(Conv2D(filters=64, kernel_size=3, padding="same", activation="relu"))
model.add(Conv2D(filters=64, kernel_size=3, activation="relu"))
model.add(MaxPool2D(pool_size=2,strides=2))

In [26]:
model.add(Conv2D(filters=128, kernel_size=3, padding="same", activation="relu"))
model.add(Conv2D(filters=128, kernel_size=3, activation="relu"))
model.add(MaxPool2D(pool_size=2,strides=2))

In [28]:
model.add(Conv2D(filters=256, kernel_size=3, padding="same", activation="relu"))
model.add(Conv2D(filters=256, kernel_size=3, activation="relu"))
model.add(MaxPool2D(pool_size=2,strides=2))

In [30]:
model.add(Conv2D(filters=512, kernel_size=3, padding="same", activation="relu"))
model.add(Conv2D(filters=512, kernel_size=3,  activation="relu"))
model.add(MaxPool2D(pool_size=2,strides=2))

In [33]:
model.add(Dropout(0.25)) # to avoid overfitting

In [35]:
model.add(Flatten())

In [37]:
model.add(Dense(units=1500,activation='relu'))

In [39]:
model.add(Dropout(0.4))

In [41]:
model.add(Dense(units=38,activation='softmax'))

In [43]:
model.compile(optimizer= tf.keras.optimizers.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [45]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 128, 128, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 128, 128, 32)        │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 64, 64, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 64, 64, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 62, 62, 64)          │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 31, 31, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_4 (Conv2D)                    │ (None, 31, 31, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_5 (Conv2D)                    │ (None, 29, 29, 128)         │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 14, 14, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_6 (Conv2D)                    │ (None, 14, 14, 256)         │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_7 (Conv2D)                    │ (None, 12, 12, 256)         │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 6, 6, 256)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_8 (Conv2D)                    │ (None, 6, 6, 512)           │       1,180,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_9 (Conv2D)                    │ (None, 4, 4, 512)           │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (None, 2, 2, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 2, 2, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 2048)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1500)                │       3,073,500 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 1500)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 38)                  │          57,038 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 7,842,762 (29.92 MB)

 Trainable params: 7,842,762 (29.92 MB)

 Non-trainable params: 0 (0.00 B)

# 

## model training

In [ ]:
training_history = model.fit(x=training_set, validation_data=validation_set,epochs=10)

Epoch 1/10
89/89 ━━━━━━━━━━━━━━━━━━━━ 396s 4s/step - accuracy: 0.0610 - loss: 3.9141 - val_accuracy: 0.1073 - val_loss: 3.3389
Epoch 2/10
89/89 ━━━━━━━━━━━━━━━━━━━━ 381s 4s/step - accuracy: 0.1686 - loss: 3.1244 - val_accuracy: 0.2157 - val_loss: 2.7430
Epoch 3/10
89/89 ━━━━━━━━━━━━━━━━━━━━ 366s 4s/step - accuracy: 0.3063 - loss: 2.5152 - val_accuracy: 0.3344 - val_loss: 2.3043
Epoch 4/10
89/89 ━━━━━━━━━━━━━━━━━━━━ 366s 4s/step - accuracy: 0.4221 - loss: 2.0523 - val_accuracy: 0.4398 - val_loss: 1.9477
Epoch 5/10
89/89 ━━━━━━━━━━━━━━━━━━━━ 366s 4s/step - accuracy: 0.5085 - loss: 1.6885 - val_accuracy: 0.4838 - val_loss: 1.6957
Epoch 6/10
89/89 ━━━━━━━━━━━━━━━━━━━━ 365s 4s/step - accuracy: 0.5682 - loss: 1.4805 - val_accuracy: 0.5531 - val_loss: 1.5067
Epoch 7/10
40/89 ━━━━━━━━━━━━━━━━━━━━ 2:02 3s/step - accuracy: 0.6347 - loss: 1.2696

In [ ]:
train_loss,train_acc= model.evaluate(training_set)

In [ ]:
print(train_loss,train_acc)

In [ ]:
val_loss,val_acc=model.evaluate(validation_set)

In [ ]:
print(val_acc,val_loss)

In [ ]:
 model.save("trained_model.keras")

In [ ]:
training_history.history

In [ ]:
# recording history in json
import json 
with open("training_his.json","w") as f:
        json.dump(training_history.history,f)

## cheking training accuracy

In [ ]:
epochs= [i for i in range(1,11)]
plt.plot(epochs,training_history.history["accuracy"],color="red",label="Training Accuracy")
plt.plot(epochs,training_history.history["val_accuracy"],color="green",label="Training Accuracy")

plt.show()

## some other metrics for model evalueation

In [ ]:
class_name= validation_set.class_names
class_name

In [ ]:
test_set =tf.keras.utils.image_dataset_from_directory(
  'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
   
)

In [ ]:
y_pred = model.predict(test_set)
y_pred

In [ ]:
predicted_catagory = tf.argmax(y_pred,axis=1)

In [ ]:
predicted_catagory

In [ ]:
true_categories = tf.concat([y for x,y in test_set],axis=0)
true_categories

In [ ]:
Y_true= tf.argmax(true_categories,axis=1)
Y_true

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
print(classification_report(Y_true,predicted_catagory,target_names= class_name))

In [ ]:
cm = confusion_matrix(Y_true,predicted_catagory)
cm

## confusion matrix visualization

In [ ]:
plt.figure(figsize=(30,30))
sns.heatmap(cm,annot_kws={'size:10'})
plt.title("Plant Disease Prediction confusion matrix ", fontsize=25)
sns.heatmap(cm)